server:
  port: 18082

spring:
  application:
    name: springcloud-consummer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false  #不注册自己
logging:
  level:
    com.wxm.springcloud.*: debug #打印sql


#微服务地址
#consummer服务
springcloud.api.url: http://springcloud-api
