server:
  port: 18081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#mybatis配置
mybatis:
  type-aliases-package: com.wxm.springcloud.po
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的配置
spring:
  application:
    name: springcloud-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/

